#!/usr/bin/env bash
#Prints time using a while loop
time=0
while [ $((time)) -le 12 ];
do
	echo "Hour: $time"
	min=1
	while [ $((min)) -lt 60 ];
	do
		echo "$min"
		let min=min+1
	done
	let time=time+1
done
